trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'book'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'book'
    customCommand: 'run build'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'book'
    Contents: '**/*.js
package-lock.json
package.json'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'drop'